### ISSUE TITLE
travis build failing

### ISSUE THREAD

**Issue by VIXXPARK** [VIXXPARK/belinkServer#42]
`Error: Dialect needs to be explicitly supplied as of v4.0.0
    at new Sequelize (/home/travis/build/VIXXPARK/belinkServer/node_modules/sequelize/lib/sequelize.js:281:13)
    at Object.<anonymous> (/home/travis/build/VIXXPARK/belinkServer/models/index.js:8:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/travis/build/VIXXPARK/belinkServer/app.js:9:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/travis/build/VIXXPARK/belinkServer/test/test01.user.spec.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.exports.requireOrImport (/home/travis/build/VIXXPARK/belinkServer/node_modules/mocha/lib/esm-utils.js:42:12)
    at Object.exports.loadFilesAsync (/home/travis/build/VIXXPARK/belinkServer/node_modules/mocha/lib/esm-utils.js:55:34)
    at Mocha.loadFilesAsync (/home/travis/build/VIXXPARK/belinkServer/node_modules/mocha/lib/mocha.js:473:19)
    at singleRun (/home/travis/build/VIXXPARK/belinkServer/node_modules/mocha/lib/cli/run-helpers.js:125:15)
    at exports.runMocha (/home/travis/build/VIXXPARK/belinkServer/node_modules/mocha/lib/cli/run-helpers.js:190:10)
    at Object.exports.handler (/home/travis/build/VIXXPARK/belinkServer/node_modules/mocha/lib/cli/run.js:362:11)
    at /home/travis/build/VIXXPARK/belinkServer/node_modules/mocha/node_modules/yargs/build/index.cjs:443:71
npm ERR! Test failed.  See above for more details.
The command "npm test" exited with 1.`

**Comment by VIXXPARK** [comment]
우선 실패한 이유는 .env파일에 대한 의존성 때문인 것 같다. 두 번째 실패한 이유는 사전에 만들어 두었던 insert문이 문제였다. 이것을 해결하는 방법이 필히 중요할 것 같다.

**Comment by VIXXPARK** [comment]
우선 timeout에 대한 해결은 의미없는 테스트 케이스를 통해 해당 timeout에 대한 해결을 시도하였다.

**Comment by VIXXPARK** [comment]
.env gitignore에 대한 해결 방안은 travis-ci 자체에 환경변수를 세팅을 해놓으면 해결된다.
